---
title: "Checks"
author: "Clare Bushman"
date: "2025-12-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##



```{r}

### wiki example matrix 

wiki <- matrix(
  c(0,5,9,9,8,
    5,0,10,10,9,
    9,10,0,8,7,
    9,10,8,0,3,
    8,9,7,3,0),
  ncol = 5,
  byrow = TRUE,
  dimnames = list(c('a','b','c','d','e'), c('a','b','c','d','e'))
)
wiki
```





```{r}
firstQ <- makeQ(wiki)

firstQ
```


```{r}
  Qmin <- which( firstQ == min(firstQ), arr.ind = TRUE)[1,]
  Qmin
  n <- nrow(wiki)
  
  aDist <- wiki[Qmin][1]
  aDist
  rows <- rowSums(wiki)
  cols <- colSums(wiki)
  
  firstD <- .5* aDist + 1/(2*(n-2)) *(rows[1] - rows[2])
  firstD
  
  d2 <- wiki[-Qmin[1], -Qmin[2]]
  d2
  d2[Qmin[2], Qmin[1]]
  
 
```
```{r}
a = Qmin[2]
b = Qmin[1]

 for(c in 1:nrow(d2) ) {
    #add 1 to account for removed row
  d2[a, c] <- .5*(wiki[a, c+1] + wiki[b, c+1] - wiki[a,b])
  d2[c,a] <- d2[a, c]
  }

  d2
  
paste(row.names(wiki)[1] ,row.names(wiki)[2])
  
```
```{r}
list(
    edges = data.frame(
      parent = c("v1","v1","v2","v2","v3"),
      child  = c("a","b","c","d","e"),
      weight = c(2,3,4,4,3)
    ),
    root = "v1"
  )

```



```{r}
library(igraph)
g <- make_graph(
  ~ Alice - Boris:Himari:Moshe, Himari - Alice:Nang:Moshe:Samira,
  Ibrahim - Nang:Moshe, Nang - Samira
)
plot(g)
```


